### ISSUE TITLE
what's the version of python and other libraries?

### ISSUE THREAD

**Issue by Ren-Yuxiang** [collindching/Waste-Sorter#1]
thanks for your sharing.i'm a student who is also intertsted in this.but there is some wrong while i runed the program.so could u share the version of python and other libraries used in your program? thank u again.

**Comment by litt1e-p** [comment]
I had trained a pth model with python 3

**Comment by collindching** [comment]
Super late, but I ran this in Python 3.7 in Jupyter. All libraries used were included in the original code. Hope this helps.
